server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

logging:
  level:
    com:
      jsyl:
        mapper: debug
        service: info
        controller: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
